version: "3.4"

services:
  kode-test-task:
    restart: always
    build: .
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
      - POSTGRES_DB='postgres'
    volumes:
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database_volume:
    
    